// <auto-generated />
using System;
using Gestion_CyberCafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_CyberCafe.Migrations
{
    [DbContext(typeof(GestionCyberContext))]
    [Migration("20260430112017_AddSeance")]
    partial class AddSeance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Connexion", b =>
                {
                    b.Property<int>("IdConnexion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConnexion"));

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeIdEmploye")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureConnexion")
                        .HasColumnType("time");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int");

                    b.Property<int>("IdPoste")
                        .HasColumnType("int");

                    b.Property<int>("PosteIdPoste")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConnexion");

                    b.HasIndex("EmployeIdEmploye");

                    b.HasIndex("PosteIdPoste");

                    b.ToTable("Connexions");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Employe", b =>
                {
                    b.Property<int>("IdEmploye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmploye"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmploye");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSeance")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeanceIdSeance")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaiement");

                    b.HasIndex("SeanceIdSeance");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Parametre", b =>
                {
                    b.Property<int>("IdParametre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametre"));

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomSysteme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixHeure")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdParametre");

                    b.ToTable("Parametres");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Poste", b =>
                {
                    b.Property<int>("IdPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPoste"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPoste");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Seance", b =>
                {
                    b.Property<int>("IdSeance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeance"));

                    b.Property<int?>("ClientIdClient")
                        .HasColumnType("int");

                    b.Property<int?>("ConnexionIdConnexion")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdConnexion")
                        .HasColumnType("int");

                    b.Property<int>("IdPoste")
                        .HasColumnType("int");

                    b.Property<int?>("PosteIdPoste")
                        .HasColumnType("int");

                    b.Property<int>("Prolongation")
                        .HasColumnType("int");

                    b.HasKey("IdSeance");

                    b.HasIndex("ClientIdClient");

                    b.HasIndex("ConnexionIdConnexion");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdConnexion");

                    b.HasIndex("IdPoste");

                    b.HasIndex("PosteIdPoste");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Connexion", b =>
                {
                    b.HasOne("Gestion_CyberCafe.ModelsR.Employe", "Employe")
                        .WithMany("Connexions")
                        .HasForeignKey("EmployeIdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_CyberCafe.ModelsR.Poste", "Poste")
                        .WithMany("Connexions")
                        .HasForeignKey("PosteIdPoste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Paiement", b =>
                {
                    b.HasOne("Gestion_CyberCafe.ModelsR.Seance", "Seance")
                        .WithMany("Paiements")
                        .HasForeignKey("SeanceIdSeance")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Seance", b =>
                {
                    b.HasOne("Gestion_CyberCafe.ModelsR.Client", null)
                        .WithMany("Seances")
                        .HasForeignKey("ClientIdClient");

                    b.HasOne("Gestion_CyberCafe.ModelsR.Connexion", null)
                        .WithMany("Seances")
                        .HasForeignKey("ConnexionIdConnexion");

                    b.HasOne("Gestion_CyberCafe.ModelsR.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestion_CyberCafe.ModelsR.Connexion", "Connexion")
                        .WithMany()
                        .HasForeignKey("IdConnexion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestion_CyberCafe.ModelsR.Poste", "Poste")
                        .WithMany()
                        .HasForeignKey("IdPoste")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestion_CyberCafe.ModelsR.Poste", null)
                        .WithMany("Seances")
                        .HasForeignKey("PosteIdPoste");

                    b.Navigation("Client");

                    b.Navigation("Connexion");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Client", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Connexion", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Employe", b =>
                {
                    b.Navigation("Connexions");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Poste", b =>
                {
                    b.Navigation("Connexions");

                    b.Navigation("Seances");
                });

            modelBuilder.Entity("Gestion_CyberCafe.ModelsR.Seance", b =>
                {
                    b.Navigation("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
